#config.yml
#first working on the api paths in this config. It id the FDIC data with the params that we will use in the request library 
api_paths:
  fdic_url: https://banks.data.fdic.gov/api/locations
  fdic_states:
    - AL
    - FL
    - GA
    - MS
    - NC
    - SC
    - TN
    - LA
  fdic_fields: NAME,OFFNAME,ADDRESS,CITY,STNAME,COUNTY,ZIP,LATITUDE,LONGITUDE,RUNDATE,UNINUM,CERT
  fdic_limit: 10000

  #census ACS 5-year data profile, county-level, southeast states
  census_url: https://api.census.gov/data/2022/acs/acs5/profile
  census_variables: NAME,DP05_0001E,DP03_0062E   # county, population, household income
  census_states:
    "01": Alabama
    "12": Florida
    "13": Georgia
    "22": Louisiana
    "28": Mississippi
    "37": North Carolina
    "45": South Carolina
    "47": Tennessee
  census_for: county:*

# hmda load data from 2024 query params 
  hmda_url: https://ffiec.cfpb.gov/v2/data-browser-api/view/csv
  hmda_states: AL,GA,FL,SC,NC,TN,MS,LA
  hmda_years: 2024
  hmda_loan_purposes: 1

#aws keys and buckets
aws:
  s3_bucket_name: bank-snowflake-project